# MkDocs Configuration

site_name: Zotify API Platform
site_description: 'A comprehensive guide to the Zotify API, its features, and architecture.'
site_author: 'Zotify Development Team'

theme:
  name: material
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

# The main documentation source directory. This is the root for the main nav.
docs_dir: 'api/docs'

# The 'monorepo' plugin will discover and merge other mkdocs.yml files.
plugins:
  - monorepo

nav:
  - 'API Documentation':
    - 'Home': 'CHANGELOG.md'
    - 'Manuals':
      - 'API Developer Guide': 'manuals/API_DEVELOPER_GUIDE.md'
      - 'CI/CD': 'manuals/CICD.md'
      - 'Error Handling': 'manuals/ERROR_HANDLING_GUIDE.md'
      - 'Logging Guide': 'manuals/LOGGING_GUIDE.md'
      - 'Operator Manual': 'manuals/OPERATOR_MANUAL.md'
      - 'System Integration Guide': 'manuals/SYSTEM_INTEGRATION_GUIDE.md'
      - 'User Manual': 'manuals/USER_MANUAL.md'
    - 'Providers':
      - 'Spotify': 'providers/SPOTIFY.md'
    - 'Reference':
      - 'API Reference': 'reference/API_REFERENCE.md'
      - 'Code File Index': 'CODE_FILE_INDEX.md'
      - 'Code Quality Index': 'CODE_QUALITY_INDEX.md'
      - 'Docs Quality Index': 'DOCS_QUALITY_INDEX.md'
      - 'Feature Specs': 'reference/FEATURE_SPECS.md'
      - 'Master Index': 'MASTER_INDEX.md'
      - 'Features':
        - 'Authentication': 'reference/features/AUTHENTICATION.md'
        - 'Automated Doc Workflow': 'reference/features/AUTOMATED_DOCUMENTATION_WORKFLOW.md'
        - 'Flexible Logging': 'reference/features/DEVELOPER_FLEXIBLE_LOGGING_FRAMEWORK.md'
        - 'Provider Extensions': 'reference/features/PROVIDER_AGNOSTIC_EXTENSIONS.md'
        - 'Provider OAuth': 'reference/features/PROVIDER_OAUTH.md'
      - 'Source Code':
        - 'ACTIONS____INIT__.py': 'reference/source/ACTIONS____INIT__.py.md'
        - 'APP.js': 'reference/source/APP.js.md'
        - 'APP.py': 'reference/source/APP.py.md'
        - 'AUDIT_API.py': 'reference/source/AUDIT_API.py.md'
        - 'AUDIT_ENDPOINTS.py': 'reference/source/AUDIT_ENDPOINTS.py.md'
        - 'AUTH.py': 'reference/source/AUTH.py.md'
        - 'AUTH_STATE.py': 'reference/source/AUTH_STATE.py.md'
        - 'BASE.py': 'reference/source/BASE.py.md'
        - 'CACHE.py': 'reference/source/CACHE.py.md'
        - 'CACHE_SERVICE.py': 'reference/source/CACHE_SERVICE.py.md'
        - 'CONFIG.py': 'reference/source/CONFIG.py.md'
        - 'CONFIG_MODELS.py': 'reference/source/CONFIG_MODELS.py.md'
        - 'CONFIG_SERVICE.py': 'reference/source/CONFIG_SERVICE.py.md'
        - 'CONSOLE_HANDLER.py': 'reference/source/CONSOLE_HANDLER.py.md'
        - 'CRUD.py': 'reference/source/CRUD.py.md'
        - 'DATABASE_JOB_HANDLER.py': 'reference/source/DATABASE_JOB_HANDLER.py.md'
        - 'DATABASE____INIT__.py': 'reference/source/DATABASE____INIT__.py.md'
        - 'DB.py': 'reference/source/DB.py.md'
        - 'DEPS.py': 'reference/source/DEPS.py.md'
        - 'DOWNLOAD.py': 'reference/source/DOWNLOAD.py.md'
        - 'DOWNLOADS.py': 'reference/source/DOWNLOADS.py.md'
        - 'DOWNLOAD_SERVICE.py': 'reference/source/DOWNLOAD_SERVICE.py.md'
        - 'ERROR_HANDLER____INIT__.py': 'reference/source/ERROR_HANDLER____INIT__.py.md'
        - 'FILTERS.py': 'reference/source/FILTERS.py.md'
        - 'FORMATTER.py': 'reference/source/FORMATTER.py.md'
        - 'FUNCTIONAL_TEST.py': 'reference/source/FUNCTIONAL_TEST.py.md'
        - 'GENERATE_ENDPOINTS_DOC.py': 'reference/source/GENERATE_ENDPOINTS_DOC.py.md'
        - 'GENERATE_OPENAPI.py': 'reference/source/GENERATE_OPENAPI.py.md'
        - 'GENERATE_SOURCE_DOCS.py': 'reference/source/GENERATE_SOURCE_DOCS.py.md'
        - 'GENERIC.py': 'reference/source/GENERIC.py.md'
        - 'GLOBALS.py': 'reference/source/GLOBALS.py.md'
        - 'HOOKS.py': 'reference/source/HOOKS.py.md'
        - 'JSON_AUDIT_HANDLER.py': 'reference/source/JSON_AUDIT_HANDLER.py.md'
        - 'LINTER.py': 'reference/source/LINTER.py.md'
        - 'LOGGING_CONFIG.py': 'reference/source/LOGGING_CONFIG.py.md'
        - 'LOGGING_FRAMEWORK____INIT__.py': 'reference/source/LOGGING_FRAMEWORK____INIT__.py.md'
        - 'LOGGING_HANDLERS____INIT__.py': 'reference/source/LOGGING_HANDLERS____INIT__.py.md'
        - 'LOGGING_SCHEMAS.py': 'reference/source/LOGGING_SCHEMAS.py.md'
        - 'LOGGING_SERVICE.py': 'reference/source/LOGGING_SERVICE.py.md'
        - 'LOG_CRITICAL.py': 'reference/source/LOG_CRITICAL.py.md'
        - 'MAIN.py': 'reference/source/MAIN.py.md'
        - 'METADATA.py': 'reference/source/METADATA.py.md'
        - 'METADATA_SERVICE.py': 'reference/source/METADATA_SERVICE.py.md'
        - 'MODELS.py': 'reference/source/MODELS.py.md'
        - 'NETWORK.py': 'reference/source/NETWORK.py.md'
        - 'NETWORK_SERVICE.py': 'reference/source/NETWORK_SERVICE.py.md'
        - 'NOTIFICATIONS.py': 'reference/source/NOTIFICATIONS.py.md'
        - 'NOTIFICATIONS_SERVICE.py': 'reference/source/NOTIFICATIONS_SERVICE.py.md'
        - 'PLAYLISTS.py': 'reference/source/PLAYLISTS.py.md'
        - 'PLAYLISTS_SERVICE.py': 'reference/source/PLAYLISTS_SERVICE.py.md'
        - 'PROVIDERS____INIT__.py': 'reference/source/PROVIDERS____INIT__.py.md'
        - 'REQUEST_ID.py': 'reference/source/REQUEST_ID.py.md'
        - 'ROUTES____INIT__.py': 'reference/source/ROUTES____INIT__.py.md'
        - 'SCHEMAS.py': 'reference/source/SCHEMAS.py.md'
        - 'SEARCH.py': 'reference/source/SEARCH.py.md'
        - 'SERVICE.py': 'reference/source/SERVICE.py.md'
        - 'SERVICES____INIT__.py': 'reference/source/SERVICES____INIT__.py.md'
        - 'SESSION.py': 'reference/source/SESSION.py.md'
        - 'SNITCH.go': 'reference/source/SNITCH.go.md'
        - 'SPOTIFY.py': 'reference/source/SPOTIFY.py.md'
        - 'SPOTIFY_CONNECTOR.py': 'reference/source/SPOTIFY_CONNECTOR.py.md'
        - 'SPOTI_CLIENT.py': 'reference/source/SPOTI_CLIENT.py.md'
        - 'SYNC.py': 'reference/source/SYNC.py.md'
        - 'SYNC_SERVICE.py': 'reference/source/SYNC_SERVICE.py.md'
        - 'SYSTEM.py': 'reference/source/SYSTEM.py.md'
        - 'TEST_AUTH_FLOW.py': 'reference/source/TEST_AUTH_FLOW.py.md'
        - 'TRACKS.py': 'reference/source/TRACKS.py.md'
        - 'TRACKS_SERVICE.py': 'reference/source/TRACKS_SERVICE.py.md'
        - 'TRIGGERS.py': 'reference/source/TRIGGERS.py.md'
        - 'USER.py': 'reference/source/USER.py.md'
        - 'USER_SERVICE.py': 'reference/source/USER_SERVICE.py.md'
        - 'WEBHOOK.py': 'reference/source/WEBHOOK.py.md'
        - 'WEBHOOKS.py': 'reference/source/WEBHOOKS.py.md'
    - 'System':
      - 'Error Handling Design': 'system/ERROR_HANDLING_DESIGN.md'
      - 'Installation': 'system/INSTALLATION.md'
      - 'Privacy Compliance': 'system/PRIVACY_COMPLIANCE.md'
      - 'Requirements': 'system/REQUIREMENTS.md'
  - 'Snitch Module': '!include ./snitch/mkdocs.yml'
  - 'Gonk TestUI Module': '!include ./Gonk/GonkUI/mkdocs.yml'


# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
