run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - golint
    - interfacer
    - maligned
    - scopelint
    - structcheck
    - varcheck
    - deadcode
    - ifshort
    - nosnakecase
    - nonamedreturns
    - testpackage
    - gochecknoinits
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - gocyclo
    - funlen
    - gocognit
    - goerr113
    - lll
    - dupl
    - goconst
    - bodyclose
    - stylecheck
    - gomnd
    - wrapcheck
    - exhaustive
    - exhaustruct
    - nlreturn
    - paralleltest
    - tparallel
    - testableexamples
    - varnamelen
    - wsl
    - godox
    - godot
    - nestif
    - prealloc
    - gci
    - gosmopolitan
    - usestdlibvars
    - musttag
    - tagliatelle
    - forbidigo
    - depguard
    - grouper
    - contextcheck
    - interfacebloat
    - reassign
    - containedctx
    - loggercheck
    - errname
    - perfsprint
    - makezero
    - nonnil
    - maintidx
    - nosprintfhostport
    - mnd
    - cyclop
    - ireturn
    - nilerr
    - forcetypeassert
    - errorlint
    - gosec
    - noctx
    - unparam
    - govet
    - staticcheck
    - unused
    - revive
    - ineffassign
    - typecheck
    - errcheck
    - exportloopref
    - gosimple
    - durationcheck
    - tenv
    - promlinter
    - unconvert
    - goprintffuncname
    - ginkgolinter
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - decorder
    - dogsled
    - dupword
    - efmt
    - errchkjson
    - errwrap
    - execinquery
    - fatcontext
    - filelinit
    - gocheckcompilerdirectives
    - goconst
    - goprintffuncname
    - gosec
    - importas
    - intrange
    - looppointer
    - mirror
    - must
    - nilnil
    - noimplicitany
    - nolintlint
    - protogetter
    - sloglint
    - spancheck
    - tagalign
    - tenv
    - thelper
    - tlog
    - unmarshal
    - wastedassign
    - whitespace
    - zerologlint
    - testifylint
    - gofumpt
    - goimports
    - misspell
    - nakedret
    - predeclared
    -thelper
    - unparam
    - whitespace
    - wrapcheck
    - ginkgolinter
    - lll
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - typecheck
    - exportloopref
    - durationcheck
    - promlinter
    - unconvert
    - goprintffuncname
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - decorder
    - dogsled
    - dupword
    - efmt
    - errchkjson
    - errwrap
    - execinquery
    - fatcontext
    - filelinit
    - gocheckcompilerdirectives
    - goconst
    - goprintffuncname
    - gosec
    - importas
    - intrange
    - looppointer
    - mirror
    - must
    - nilnil
    - noimplicitany
    - nolintlint
    - protogetter
    - sloglint
    - spancheck
    - tagalign
    - tenv
    - thelper
    - tlog
    - unmarshal
    - wastedassign
    - whitespace
    - zerologlint
    - testifylint
    - gofumpt
    - goimports
    - misspell
    - nakedret
    - predeclared
    -thelper
    - unparam
    - whitespace
    - wrapcheck
    - ginkgolinter
    - lll
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - typecheck
    - exportloopref
    - durationcheck
    - promlinter
    - unconvert
    - goprintffuncname
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - decorder
    - dogsled
    - dupword
    - efmt
    - errchkjson
    - errwrap
    - execinquery
    - fatcontext
    - filelinit
    - gocheckcompilerdirectives
    - goconst
    - goprintffuncname
    - gosec
    - importas
    - intrange
    - looppointer
    - mirror
    - must
    - nilnil
    - noimplicitany
    - nolintlint
    - protogetter
    - sloglint
    - spancheck
    - tagalign
    - tenv
    - thelper
    - tlog
    - unmarshal
    - wastedassign
    - whitespace
    - zerologlint
    - testifylint
    - gofumpt
    - goimports
    - misspell
    - nakedret
    - predeclared
    -thelper
    - unparam
    - whitespace
    - wrapcheck
    - ginkgolinter
    - lll
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - typecheck
    - exportloopref
    - durationcheck
    - promlinter
    - unconvert
    - goprintffuncname
    - asasalint
    - asciicheck
    - bidichk
    - canonicalheader
    - decorder
    - dogsled
    - dupword
    - efmt
    - errchkjson
    - errwrap
    - execinquery
    - fatcontext
    - filelinit
    - gocheckcompilerdirectives
    - goconst
    - goprintffuncname
    - gosec
    - importas
    - intrange
    - looppointer
    - mirror
    - must
    - nilnil
    - noimplicitany
    - nolintlint
    - protogetter
    - sloglint
    - spancheck
    - tagalign
    - tenv
    - thelper
    - tlog
    - unmarshal
    - wastedassign
    - whitespace
    - zerologlint
    - testifylint
    - gofumpt
    - goimports
    - misspell
    - nakedret
    - predeclared
    -thelper
    - unparam
    - whitespace
    - wrapcheck
    - ginkgolinter
    - lll

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - bodyclose
        - stylecheck
        - gomnd
        - wrapcheck
        - exhaustive
        - exhaustruct
        - nlreturn
        - paralleltest
        - tparallel
        - testableexamples
        - varnamelen
        - wsl
        - godox
        - godot
        - nestif
        - prealloc
        - gci
        - gosmopolitan
        - usestdlibvars
        - musttag
        - tagliatelle
        - forbidigo
        - depguard
        - grouper
        - contextcheck
        - interfacebloat
        - reassign
        - containedctx
        - loggercheck
        - errname
        - perfsprint
        - makezero
        - nonnil
        - maintidx
        - nosprintfhostport
        - mnd
        - cyclop
        - ireturn
        - nilerr
        - forcetypeassert
        - errorlint
        - gosec
        - noctx
        - unparam
        - govet
        - staticcheck
        - unused
        - revive
        - ineffassign
        - typecheck
        - exportloopref
        - gosimple
        - durationcheck
        - tenv
        - promlinter
        - unconvert
        - goprintffuncname
        - ginkgolinter
        - asasalint
        - asciicheck
        - bidichk
        - canonicalheader
        - decorder
        - dogsled
        - dupword
        - efmt
        - errchkjson
        - errwrap
        - execinquery
        - fatcontext
        - filelinit
        - gocheckcompilerdirectives
        - goconst
        - goprintffuncname
        - gosec
        - importas
        - intrange
        - looppointer
        - mirror
        - must
        - nilnil
        - noimplicitany
        - nolintlint
        - protogetter
        - sloglint
        - spancheck
        - tagalign
        - tenv
        - thelper
        - tlog
        - unmarshal
        - wastedassign
        - whitespace
        - zerologlint
        - testifylint
        - gofumpt
        - goimports
        - misspell
        - nakedret
        - predeclared
        -thelper
        - unparam
        - whitespace
        - wrapcheck
        - ginkgolinter
        - lll
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - revive
        - typecheck
        - exportloopref
        - durationcheck
        - promlinter
        - unconvert
        - goprintffuncname
        - asasalint
        - asciicheck
        - bidichk
        - canonicalheader
        - decorder
        - dogsled
        - dupword
        - efmt
        - errchkjson
        - errwrap
        - execinquery
        - fatcontext
        - filelinit
        - gocheckcompilerdirectives
        - goconst
        - goprintffuncname
        - gosec
        - importas
        - intrange
        - looppointer
        - mirror
        - must
        - nilnil
        - noimplicitany
        - nolintlint
        - protogetter
        - sloglint
        - spancheck
        - tagalign
        - tenv
        - thelper
        - tlog
        - unmarshal
        - wastedassign
        - whitespace
        - zerologlint
        - testifylint
        - gofumpt
        - goimports
        - misspell
        - nakedret
        - predeclared
        -thelper
        - unparam
        - whitespace
        - wrapcheck
        - ginkgolinter
        - lll
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - revive
        - typecheck
        - exportloopref
        - durationcheck
        - promlinter
        - unconvert
        - goprintffuncname
        - asasalint
        - asciicheck
        - bidichk
        - canonicalheader
        - decorder
        - dogsled
        - dupword
        - efmt
        - errchkjson
        - errwrap
        - execinquery
        - fatcontext
        - filelinit
        - gocheckcompilerdirectives
        - goconst
        - goprintffuncname
        - gosec
        - importas
        - intrange
        - looppointer
        - mirror
        - must
        - nilnil
        - noimplicitany
        - nolintlint
        - protogetter
        - sloglint
        - spancheck
        - tagalign
        - tenv
        - thelper
        - tlog
        - unmarshal
        - wastedassign
        - whitespace
        - zerologlint
        - testifylint
        - gofumpt
        - goimports
        - misspell
        - nakedret
        - predeclared
        -thelper
        - unparam
        - whitespace
        - wrapcheck
        - ginkgolinter
        - lll
