name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov
        cd api
        pip install .

    - name: Run tests with coverage check
      run: |
        cd api
        mkdir -p storage
        APP_ENV=development pytest --cov=src/zotify_api --cov-fail-under=85 tests/
